package testutil

import (
	"time"

	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/types"
)

// IgnoreKubernetesMetadata returns cmp.Options that ignore runtime-generated Kubernetes fields.
// Use this when comparing expected vs actual Kubernetes resources in tests.
func IgnoreKubernetesMetadata() cmp.Options {
	return cmp.Options{
		// Ignore ObjectMeta fields that are set by the API server
		cmpopts.IgnoreFields(metav1.ObjectMeta{},
			"UID",                   // Generated by API server
			"ResourceVersion",       // Changes on every update
			"Generation",            // Auto-incremented
			"CreationTimestamp",     // Set at creation time
			"DeletionTimestamp",     // Set when deletion starts
			"DeletionGracePeriodSeconds",
			"ManagedFields",         // Server-side apply tracking
			"SelfLink",              // Deprecated but may exist
		),

		// Ignore TypeMeta fields (often empty in client responses)
		cmpopts.IgnoreFields(metav1.TypeMeta{},
			"Kind",
			"APIVersion",
		),

		// Ignore Status subresource (tested separately)
		cmpopts.IgnoreFields(metav1.Condition{},
			"LastTransitionTime",    // Time-based, always different
		),

		// Ignore time.Time fields (always different)
		cmpopts.IgnoreTypes(time.Time{}),
		cmpopts.IgnoreTypes(metav1.Time{}),

		// Ignore UID type
		cmpopts.IgnoreTypes(types.UID("")),
	}
}

// IgnoreObjectMetaCompletely ignores the entire ObjectMeta (use when you only care about Spec).
func IgnoreObjectMetaCompletely() cmp.Option {
	return cmpopts.IgnoreFields(metav1.ObjectMeta{})
}

// IgnoreStatus ignores the Status subresource completely.
func IgnoreStatus() cmp.Option {
	return cmpopts.IgnoreFields(struct{ Status interface{} }{}, "Status")
}

// CompareOptions returns common options for comparing Kubernetes objects.
// By default, ignores metadata and status.
func CompareOptions() cmp.Options {
	return cmp.Options{
		IgnoreKubernetesMetadata(),
		IgnoreStatus(),
	}
}

// CompareSpec returns options for comparing only Spec fields.
// Ignores all metadata and status.
func CompareSpecOnly() cmp.Options {
	return cmp.Options{
		IgnoreObjectMetaCompletely(),
		IgnoreStatus(),
	}
}
