package testutil

import (
	"time"

	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	appsv1 "k8s.io/api/apps/v1"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/types"
)

// IgnoreMetaRuntimeFields returns cmp.Options that ignore runtime-generated
// Kubernetes fields. Use this when comparing expected vs actual Kubernetes
// resources in tests.
func IgnoreMetaRuntimeFields() cmp.Options {
	return cmp.Options{
		// Ignore ObjectMeta fields that are set by the API server
		cmpopts.IgnoreFields(metav1.ObjectMeta{},
			"UID",               // Generated by API server
			"ResourceVersion",   // Changes on every update
			"Generation",        // Auto-incremented
			"CreationTimestamp", // Set at creation time
			"DeletionTimestamp", // Set when deletion starts
			"DeletionGracePeriodSeconds",
			"ManagedFields", // Server-side apply tracking
			"SelfLink",      // Deprecated but may exist
		),

		// Ignore TypeMeta fields (often empty in client responses)
		// NOTE: This is commented out as this has no impact in most cases.
		// Consider removing this altogether.
		// cmpopts.IgnoreFields(metav1.TypeMeta{},
		// 	"Kind",
		// 	"APIVersion",
		// ),

		// Ignore Status subresource (tested separately)
		cmpopts.IgnoreFields(metav1.Condition{},
			"LastTransitionTime", // Time-based, always different
		),

		// Ignore time.Time fields (always different)
		cmpopts.IgnoreTypes(time.Time{}),
		cmpopts.IgnoreTypes(metav1.Time{}),

		// Ignore UID type
		cmpopts.IgnoreTypes(types.UID("")),
	}
}

// IgnoreServiceRuntimeFields ignores Service fields that are assigned at
// runtime by Kubernetes.
func IgnoreServiceRuntimeFields() cmp.Option {
	return cmpopts.IgnoreFields(corev1.ServiceSpec{},
		// Randomly allocated by Kubernetes from service CIDR range
		"ClusterIP",
		"ClusterIPs",

		// Derived from cluster IP stack configuration (IPv4, IPv6, or dual-stack)
		"IPFamilies",
		"IPFamilyPolicy",

		// Default policy set based on cluster configuration
		"InternalTrafficPolicy",

		// Defaults to "None"
		"SessionAffinity",
	)
}

// IgnoreStatefulSetRuntimeFields ignores StatefulSet status fields that are
// updated at runtime by the StatefulSet controller.
func IgnoreStatefulSetRuntimeFields() cmp.Option {
	return cmpopts.IgnoreFields(appsv1.StatefulSetStatus{},
		// Replica state counters (updated by controller based on pod status)
		"Replicas",
		"ReadyReplicas",
		"CurrentReplicas",
		"UpdatedReplicas",
		"AvailableReplicas",

		// Revision tracking (generated hashes by controller for rolling updates)
		"CurrentRevision",
		"UpdateRevision",

		// Controller reconciliation metadata
		"ObservedGeneration", // Tracks which spec generation was reconciled
		"CollisionCount",     // Counter for name collision avoidance
		"Conditions",         // Status conditions updated by controller
	)
}

// IgnoreDeploymentRuntimeFields ignores Deployment status fields that are
// updated at runtime by the Deployment controller.
func IgnoreDeploymentRuntimeFields() cmp.Option {
	return cmpopts.IgnoreFields(appsv1.DeploymentStatus{},
		// Replica state counters (updated by controller based on ReplicaSet status)
		"Replicas",
		"ReadyReplicas",
		"AvailableReplicas",
		"UnavailableReplicas",
		"UpdatedReplicas",

		// Controller reconciliation metadata
		"ObservedGeneration", // Tracks which spec generation was reconciled
		"CollisionCount",     // Counter for ReplicaSet name collision avoidance
		"Conditions",         // Status conditions updated by controller
	)
}

// IgnorePodSpecDefaults ignores all PodSpec and Container defaults applied by
// Kubernetes, including ImagePullPolicy. Use when you only care about
// explicitly set fields.
func IgnorePodSpecDefaults() cmp.Option {
	return cmp.Options{
		cmpopts.IgnoreFields(corev1.PodSpec{},
			// Pod lifecycle defaults
			"RestartPolicy",                 // Defaults to "Always"
			"TerminationGracePeriodSeconds", // Defaults to 30
			"DNSPolicy",                     // Defaults to "ClusterFirst"
			"SchedulerName",                 // Defaults to "default-scheduler"
			"SecurityContext",               // Default PodSecurityContext applied
		),
		cmpopts.IgnoreFields(corev1.Container{},
			// Container defaults
			"TerminationMessagePath",   // Defaults to "/dev/termination-log"
			"TerminationMessagePolicy", // Defaults to "File"
			"ImagePullPolicy",          // Defaults: Always for :latest, IfNotPresent otherwise
		),
	}
}

// IgnorePodSpecDefaultsExceptPullPolicy ignores PodSpec defaults but preserves
// ImagePullPolicy for verification. Use when you want to assert ImagePullPolicy
// is correct.
func IgnorePodSpecDefaultsExceptPullPolicy() cmp.Option {
	return cmp.Options{
		cmpopts.IgnoreFields(corev1.PodSpec{},
			// Pod lifecycle defaults
			"RestartPolicy",                 // Defaults to "Always"
			"TerminationGracePeriodSeconds", // Defaults to 30
			"DNSPolicy",                     // Defaults to "ClusterFirst"
			"SchedulerName",                 // Defaults to "default-scheduler"
			"SecurityContext",               // Default PodSecurityContext applied
		),
		cmpopts.IgnoreFields(corev1.Container{},
			// Container termination logging
			"TerminationMessagePath",   // Defaults to "/dev/termination-log"
			"TerminationMessagePolicy", // Defaults to "File"
			// Note: ImagePullPolicy NOT ignored - preserved for assertions
		),
	}
}

// IgnoreStatefulSetSpecDefaults ignores StatefulSetSpec fields that have
// Kubernetes defaults applied.
func IgnoreStatefulSetSpecDefaults() cmp.Option {
	return cmpopts.IgnoreFields(appsv1.StatefulSetSpec{},
		// StatefulSet-specific defaults
		"PodManagementPolicy",                  // Defaults to "OrderedReady"
		"RevisionHistoryLimit",                 // Defaults to 10
		"UpdateStrategy",                       // Defaults to RollingUpdate with partition=0
		"PersistentVolumeClaimRetentionPolicy", // Defaults to Retain/Retain
	)
}

// IgnoreDeploymentSpecDefaults ignores DeploymentSpec fields that have
// Kubernetes defaults applied.
func IgnoreDeploymentSpecDefaults() cmp.Option {
	return cmpopts.IgnoreFields(
		appsv1.DeploymentSpec{},
		// Deployment-specific defaults
		"Strategy",                // Defaults to RollingUpdate with MaxSurge=25%, MaxUnavailable=25%
		"RevisionHistoryLimit",    // Defaults to 10
		"ProgressDeadlineSeconds", // Defaults to 600 seconds (10 minutes)
	)
}

// IgnoreObjectMetaCompletely ignores the entire ObjectMeta (use when you only
// care about Spec).
func IgnoreObjectMetaCompletely() cmp.Option {
	return cmpopts.IgnoreFields(metav1.ObjectMeta{})
}

// IgnoreStatus ignores the Status subresource completely.
func IgnoreStatus() cmp.Option {
	return cmpopts.IgnoreFields(struct{ Status any }{}, "Status")
}

// CompareOptions returns common options for comparing Kubernetes objects.
// By default, ignores metadata and status.
func CompareOptions() cmp.Options {
	return cmp.Options{
		IgnoreMetaRuntimeFields(),
		IgnoreStatus(),
	}
}

// CompareSpecOnly returns options for comparing only Spec fields.
// Ignores all metadata and status.
func CompareSpecOnly() cmp.Options {
	return cmp.Options{
		IgnoreObjectMetaCompletely(),
		IgnoreStatus(),
	}
}
