apiVersion: multigres.com/v1alpha1
kind: Shard
metadata:
  name: kind-shard-sample
  namespace: default
spec:
  # ============================================================================
  # MVP Configuration (Currently Active)
  # ============================================================================
  # The MVP (Minimum Viable Product) has strict validation requirements:
  # - Database must be "postgres"
  # - TableGroup must be "default"
  # - Shard name must be "0-inf" for default tablegroup (unsharded/range mode)

  databaseName: postgres
  tableGroupName: default
  shardName: "0-inf"

  # ============================================================================
  # Original E2E Configuration (Commented Out)
  # ============================================================================
  # For future e2e testing with custom databases/tablegroups, uncomment below
  # and comment out the MVP config above:
  #
  # databaseName: mydb
  # tableGroupName: users
  # shardName: "0"

  # Container images for shard components
  images:
    multiorch: ghcr.io/multigres/multigres:main
    multipooler: ghcr.io/multigres/multigres:main
    postgres: postgres:16-alpine

  # Reference to the global topology server
  globalTopoServer:
    address: kind-toposerver-sample:2379
    rootPath: /multigres/global
    implementation: etcd2

  # MultiOrch configuration for shard orchestration
  multiorch:
    cells:
      - zone-a
    replicas: 1
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi

  # Shard pools - different types of PostgreSQL replicas
  pools:
    # Primary "eligible" pool, with unique name
    pool-1:
      type: readWrite
      cells:
        - zone-a
      replicasPerCell: 3

      # Storage configuration - kind uses local storage provisioner
      storage:
        size: 1Gi

      # PostgreSQL container configuration - lower resources for kind
      postgres:
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi

      # MultiPooler container configuration
      multipooler:
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi

    # Read replica pool
    pool-readonly:
      type: readOnly
      cells:
        - zone-a
      replicasPerCell: 3

      storage:
        size: 1Gi

      postgres:
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi

      multipooler:
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
