apiVersion: multigres.com/v1alpha1
kind: Cell
metadata:
  name: kind-cell-sample
  namespace: default
spec:
  # Logical name of the cell
  name: zone-a

  # Physical zone placement (use either 'zone' or 'region', not both)
  zone: us-west-1a

  # Container image for multigateway
  multigatewayImage: ghcr.io/multigres/multigres:main

  # MultiGateway deployment - query routing
  multigateway:
    replicas: 1
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi

  # Reference to the global topology server
  globalTopoServer:
    address: kind-global-topo:2379
    rootPath: /multigres/global
    implementation: etcd2

  # Cell-local topology server configuration (optional)
  # If specified, creates a local etcd cluster for this cell
  topoServer:
    etcd:
      image: quay.io/coreos/etcd:v3.5.12
      replicas: 1
      storage:
        size: 1Gi
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi

  # List of all cells in the cluster for discovery
  allCells:
    - zone-a

  # Topology reconciliation settings
  topologyReconciliation:
    registerCell: true
    prunePoolers: true
