apiVersion: multigres.com/v1alpha1
kind: TopoServer
metadata:
  name: kind-toposerver-sample
  namespace: default
spec:
  # ============================================================================
  # MVP Configuration (Currently Active)
  # ============================================================================
  # Minimal etcd configuration compatible with MVP requirements

  # Etcd configuration for the topology server
  etcd:
    # etcd container image
    image: quay.io/coreos/etcd:v3.5.12

    # Number of etcd replicas (must be odd: 1, 3, 5, etc.)
    # Using 1 replica for kind to minimize resource usage
    replicas: 1

    # Storage configuration for etcd data - kind uses local storage provisioner
    storage:
      size: 1Gi
      accessModes:
        - ReadWriteOnce

    # Resource requirements for etcd containers - lower for kind
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
