apiVersion: multigres.com/v1alpha1
kind: Shard
metadata:
  name: kind-shard-sample
  namespace: default
spec:
  # Shard identification
  databaseName: mydb
  tableGroupName: users
  shardName: "0"

  # Container images for shard components
  images:
    multiorch: ghcr.io/multigres/multigres:main
    multipooler: ghcr.io/multigres/multigres:main
    postgres: postgres:16-alpine

  # Reference to the global topology server
  globalTopoServer:
    address: kind-global-topo:2379
    rootPath: /multigres/global
    implementation: etcd2

  # MultiOrch configuration for shard orchestration
  multiorch:
    cells:
      - zone-a
    replicas: 1
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi

  # Shard pools - different types of PostgreSQL replicas
  pools:
    # Primary replica pool
    primary:
      type: readWrite
      cells:
        - zone-a
      replicasPerCell: 1

      # Storage configuration - kind uses local storage provisioner
      storage:
        size: 1Gi

      # PostgreSQL container configuration - lower resources for kind
      postgres:
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi

      # MultiPooler container configuration
      multipooler:
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi

    # Read replica pool
    replica:
      type: readOnly
      cells:
        - zone-a
      replicasPerCell: 1

      storage:
        size: 1Gi

      postgres:
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi

      multipooler:
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
