apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: multigres-operator
rules:
  # MultiGres CRDs
  - apiGroups: ["multigres.com"]
    resources: ["*"]
    verbs: ["*"]
  # Core resources
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps", "secrets", "persistentvolumeclaims"]
    verbs: ["*"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["*"]
  # Events for status updates
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
  # Leases for leader election
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["*"]
