name: Generate and verify manifests

on:
  workflow_call: {}

jobs:
  verify-manifests:
    name: Generate and verify manifests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Install Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version-file: ./go.mod

      - name: Verify manifests
        run: make verify
