name: Build & Release

on:
  workflow_call:
    inputs:
      architectures:
        description: A JSON list of GOARCH values for which to build
        default: '["amd64", "arm64"]'
        required: false
        type: string
      push-container-image:
        description: Whether to push the resulting container image to the registry
        default: false
        required: false
        type: boolean

permissions:
  contents: write
  packages: write
  security-events: write

jobs:
  test-go:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: go.mod

      - name: Run tests
        run: go test ./... -coverprofile=./cover.out -covermode=atomic -coverpkg=./...


  build-scan-push-container:
    needs: [ test-go ]
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4.0.0

      - name: Set up Docker for multi-platform
        uses: docker/setup-docker-action@1a6edb0ba9ac496f6850236981f15d8f9a82254d # v5.0.0
        with:
          daemon-config: |
            {
              "features": {
                "containerd-snapshotter": true
              }
            }

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

      - name: Log into registry
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute short SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> "$GITHUB_ENV"

      - name: Build container image
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7.0.0
        with:
          context: .
          file: Dockerfile
          platforms: linux/${{ join(fromJson(inputs.architectures), ',linux/') }}
          load: true
          push: false
          tags: "ghcr.io/${{ github.repository }}:${{ github.sha }}"
          provenance: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=oci,dest=container-image.tar
          build-args: |
            VERSION=${{ env.SHORT_SHA }}
            GIT_COMMIT=${{ github.sha }}
            BUILD_DATE=${{ github.event.head_commit.timestamp }}

      - name: Push to registry (sha)
        run: |
          IMAGE="ghcr.io/${{ github.repository }}"
          docker push "$IMAGE:${{ github.sha }}"

      # grype requires that the container image be pushed already because
      # the scanner runs in a container with a different local registry
      - name: Scan final image with grype
        id: scan
        uses: anchore/scan-action@e1165082ffb1fe366ebaf02d8526e7c4989ea9d2 # v7.4.0
        continue-on-error: true
        with:
          cache-db: true
          image: "ghcr.io/${{ github.repository }}:${{ github.sha }}"
          output-file: grype.sarif
          severity-cutoff: high
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@38697555549f1db7851b81482ff19f1fa5c4fedc # v4.34.1
        with:
          sarif_file: grype.sarif
      - name: Check success or failure
        if: ${{ steps.scan.outcome == 'failure' }}
        run: |-
          jq '.runs[0].results | map(select(.level == "error"))' grype.sarif
          exit 1

      - name: Push to registry (latest)
        if: ${{ inputs.push-container-image }}
        run: |
          IMAGE="ghcr.io/${{ github.repository }}"
          docker tag "$IMAGE:${{ github.sha }}" "$IMAGE:latest"
          docker push "$IMAGE:latest"

  validate-installer:
    needs: [ test-go ]
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: go.mod

      - name: Validate install manifests
        run: make build-installer
