name: Build main

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
      - "**/*.txt"

permissions:
  contents: write
  packages: write
  security-events: write

jobs:
  build:
    name: Build
    uses: ./.github/workflows/_reusable-build-changed.yaml

  run:
    uses: ./.github/workflows/build-and-release.yaml
    with:
      push-container-image: true

  coverage:
    name: Coverage
    permissions:
      contents: read
      pull-requests: write
    uses: ./.github/workflows/_reusable-test-coverage.yaml
    with:
      COVERAGE_THRESHOLD: 70

  e2e:
    name: "E2E (${{ matrix.test }})"
    strategy:
      fail-fast: false
      matrix:
        test: [minimal, inline, templated, deletion]
    permissions:
      contents: read
    uses: ./.github/workflows/_reusable-e2e.yaml
    with:
      test-spec: ${{ matrix.test }}
      mode: shared
