name: CI

on:
  pull_request:
    paths-ignore:
      - "**/*.md"
      - "**/*.txt"

permissions:
  contents: write
  packages: write

jobs:
  scan-dependencies:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: actions/dependency-review-action@a1d282b36b6f3519aa1f3fc636f609c47dddb294 # v5.0.0
  build:
    name: Build
    uses: ./.github/workflows/_reusable-build-changed.yaml
  manifests:
    name: Manifests
    uses: ./.github/workflows/_reusable-manifests.yaml
  coverage:
    name: Coverage
    permissions:
      contents: read
    uses: ./.github/workflows/_reusable-test-coverage.yaml
    with:
      COVERAGE_THRESHOLD: 70
