name: Scan intermediate image

on:
  schedule:
    - cron: '0 6 * * *' # daily at 06:00 UTC
  workflow_dispatch: {}

permissions:
  security-events: write

jobs:
  scan-intermediate-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Scan intermediate image with grype
        id: scan
        uses: anchore/scan-action@e1165082ffb1fe366ebaf02d8526e7c4989ea9d2 # v7.4.0
        continue-on-error: true
        with:
          cache-db: true
          image: "golang:1.25.8-alpine3.23" # sync this with Dockerfile
          output-file: grype.sarif
          severity-cutoff: high
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@38697555549f1db7851b81482ff19f1fa5c4fedc # v4.34.1
        with:
          sarif_file: grype.sarif
      - name: Check success or failure
        if: ${{ steps.scan.outcome == 'failure' }}
        run: |-
          jq '.runs[0].results | map(select(.level == "error"))' grype.sarif
          exit 1
